name: bi-group

services:

  data-db:
    image: postgres:18
    restart: always
    volumes:
      - data-db-vol:/var/lib/postgresql
    env_file:
      - ./env/data-db.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - compose-network

  metabase-db:
    image: postgres:18
    restart: always
    volumes:
      - metabase-db-vol:/var/lib/postgresql
    env_file:
      - ./env/metabase-db.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    depends_on:
      data-db:
        condition: service_healthy
      metabase-db:
        condition: service_healthy

    networks:
      - compose-network

  metabase-bi:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    env_file:
      - ./env/metabase-bi.env

    depends_on:
      metabase-db:
        condition: service_healthy

    networks:
      - compose-network

volumes:
  data-db-vol:
  metabase-db-vol:

networks:
  compose-network:
    driver: bridge